# -*- coding: utf-8 -*-
"""pandas.tutorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MCnZrNrOD858ybR2PYBH7PphezOxpA7
"""

import pandas as pd
# crating a DataFrame from a dictionary
data=[
    ['Shri'   , 14 ,  ' pondy '],
     ['kabi'  , 21 ,  ' chennai '],
      ['Elaki',35  ,  ' bangalore '],

]
df=pd.DataFrame(data, columns=['Name','Age','       City   '])
print("DataFrame from list of lists:\n",df)

import pandas as pd
df=pd.read_csv('/content/heart (3).csv')
print(df)

import pandas as pd
data={
    'Name':['Shri','kabi','Elaki','sharan','sashi','dhiya','danu','sreeja','harini','vanitha'],
    'Age':[14,21,35,23,24,26,27,28,110,29],
    'City':['pondy','chennai','bangalore','delhi','france','UK','new york','goa','mattuthavani','UAE']
}

df=pd.DataFrame(data)
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

#selecting a single column
print(df['Name'])
print(df,[['Name','Age']])
print(df.iloc[0])
print(df[df['Age']>30])

#adding a new column
df['salary']=[70000,80000,90000,40000,500000,60000,60000,70000,5000000000,199999]
print(df)
#modifying an existing column
df['Age'] = df['Age']+40
print(df)

#creating a sample dataframe with missing values
data={
    'Name':['shri','dhiya','zirva'],
    'Age':[25,None,33,12],

}
df=pd.DataFrame(data)
df_dropped =df.dropna()
print(df_dropped)